### ISSUE TITLE
Catatan pendampingan

### ISSUE THREAD

**Issue by vaijho** [datum-indo/cmslbh#15]
Catatan Pendampingan: tidak bisa diisi karena Kabid belum menetapkan. ataupun ketika sebelumnya belum ada request, bagaimana cara request susulan? apakah ada?

Urutan dari catatan pendampingan belum berdasarkan waktu pendampingan. jadi saat diisi diakhir, tidak berurut berdasarkan waktu

**Comment by syaldi** [comment]
Tidak bisa diisi selama belum ada penetapan. Ini juga terkait dengan request, jadi alurnya harus ada reguest - approve - penunjukan baru bisa lanjut
