### ISSUE TITLE
Tampilan Informasi Klien saat klik nama klien di Data Permohonan

### ISSUE THREAD

**Issue by vaijho** [datum-indo/cmslbh#24]
Mohon dapat ditambahkan field  Data detil klien untuk disabilitas Dan kebutuhannya, Jenis Kelamin, Kota, SKTM/Penggantinya sebagaimana contoh berikut:
![ck-detail-info](https://user-images.githubusercontent.com/167390/134146551-f71bb0ba-fa70-444e-945f-37c13b86182c.jpg)

**Comment by syaldi** [comment]
sama dengan #5
